spring:
  cloud:
    gateway:
     # default-filters:
      #  - name: IDLFilter
      #    args:
            #analysis: Detection
        #    analysis: Explanation
            #analysis: None
      routes:
        - id: YelpAPI
          uri: https://api.yelp.com
          predicates:
            - Path=/v3/businesses/**
          filters:
            - name: IDLFilter
              args:
                #analysis: Detection
                #analysis: Explanation
                analysis: None
        - id: YelpTransactionsAPI
          uri: https://api.yelp.com
          predicates:
            - Path=/v3/transactions/**
        - id: BoxFoldersAPI
          uri: https://api.box.com
          predicates:
            - Path=/2.0/**
        - id: GitHubAPI
          uri: https://api.github.com
          predicates:
            - Path=/user/**
        - id: AmadeusFlightAPI
          uri: https://test.api.amadeus.com
          predicates:
            - Path=/v2/shopping/**
        - id: AmadeusHotelAPI
          uri: https://test.api.amadeus.com
          predicates:
            - Path=/v3/shopping/**
        - id: YoutubeAPI
          uri: https://youtube.googleapis.com
          predicates:
            - Path=/youtube/**
        - id: DHLAPI
          uri: https://api.dhl.com
          predicates:
            - Path=/location-finder/v1/**
        - id: FSQAPI
          uri: https://api.foursquare.com
          predicates:
            - Path=/v3/places/**
        - id: TumblrAPI
          uri: https://api.tumblr.com
          predicates:
            - Path=/v2/blog/**
        #- id: OMDbAPI
        #  uri: http://omdbapi.com
        #  predicates:
        #    - Path=/
